/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/value`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/location`; params?: Router.UnknownInputParams; } | { pathname: `/ingredient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/ingredient/[id]/recipe`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/ingredient/[id]/source`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/value`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/location`; params?: Router.UnknownOutputParams; } | { pathname: `/ingredient/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/ingredient/[id]/recipe`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/ingredient/[id]/source`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/onboarding/location${`?${string}` | `#${string}` | ''}` | `/onboarding/value${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/settings/location${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/value`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/settings/location`; params?: Router.UnknownInputParams; } | `/ingredient/${Router.SingleRoutePart<T>}` | `/ingredient/${Router.SingleRoutePart<T>}/recipe` | `/ingredient/${Router.SingleRoutePart<T>}/source` | { pathname: `/ingredient/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/ingredient/[id]/recipe`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/ingredient/[id]/source`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
